apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-app-a-only
  labels:
    app: postgres
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: postgres
      release: {{ .Release.Name }}

  policyTypes:
    - Ingress                # We're controlling inbound traffic

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: app-a
              release: app-a
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: backend
      ports:
        - protocol: TCP
          port: 5432
