apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  labels:
    app: postgres
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce    # Single node can mount read-write
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClassName }}
