apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  labels:
    app: postgres
    release: {{ .Release.Name }}
# Opaque = generic key-value pairs (base64-encoded by K8s automatically)
type: Opaque
# stringData is the human-readable form — K8s base64-encodes it into `data` automatically
stringData:
  POSTGRES_DB: {{ .Values.auth.database }}
  POSTGRES_USER: {{ .Values.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.auth.password }}
