apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: postgres
    release: {{ .Release.Name }}
spec:
  # ClusterIP = internal-only (no external access) — the default and most secure
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app: postgres
    release: {{ .Release.Name }}
