apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: app-a
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  # Route traffic to pods matching these labels
  selector:
    app: app-a
    release: {{ .Release.Name }}
